### ISSUE TITLE
Minor remark: data type missing

### ISSUE THREAD

**Issue by AdriaJ** [matthieumeo/pyxu#2]
Within **pycsou.core.solver**, the returned type should probably be **float** for the following abstract method of **GenericIterativeAlgorithm**.

```
    @abstractmethod
    def stopping_metric(self):
        r"""
        Stopping metric.
        """
        pass
```

**Comment by SepandKashani** [comment]
This problem is related to Pycsou v1.
Pycsou v2's `Solver` API works differently and solves the equivalent issue.
We can therefore safely close this issue.
