### ISSUE TITLE
Treat exception with svds when k=1

### ISSUE THREAD

**Issue by AdriaJ** [matthieumeo/pyxu#4]
When trying to compute the singular values with ```spls.svds```, Python raises an error when the dimension of the operator from which it tries to compute the svd is of size one. Indeed, this function needs the number of value to return to be strictly lower than the minimal dimension size of the operator. In the case of a vector, calling the function should return the euclidian norm of the vector I guess.
This problem happens when computing the Lipschitz constant of an operator for which one of the dimension has size one (basically a vector instead of a matrix).

**Comment by SepandKashani** [comment]
This issue is solved in [v2-dev](https://github.com/matthieumeo/pycsou/tree/v2-dev).
