### ISSUE TITLE
Suggestion for code simplification

### ISSUE THREAD

**Issue by AdriaJ** [matthieumeo/pyxu#5]
The two functions **`update_iterand`** from file `proxalgs.py` start with a test on the iteration number:
```
    def update_iterand(self) -> dict:
        if self.iter == 0:
            x, z = self.init_iterand.values()
        else:
            x, z = self.iterand.values()
```

I think this test is not required as the information we are looking for is already stored in the dictionary **`old_iterand`**. The code could then be replaced by:
```
x, z = self.old_iterand.values()
```
However, in case of modifications of the variables `x, z`, it might be required to create a deepcopy of the variables (not sure).

Same goes for
```
x, x_old, t_old = self.old_iterand.values()
```
for **`APGD`**.

**Comment by SepandKashani** [comment]
This issue is solved in Pycsou v2's `PGD` solver.
