### ISSUE TITLE
GenericIterativeAlgorithms always "converges"

### ISSUE THREAD

**Issue by AdriaJ** [matthieumeo/pyxu#6]
The `iterate()` method from **`GenericIterativeAlgorithm`** class from file *`solver.py`* always returns
```
self.converged = True
```
which might not be accurate, for instance if it stops after reaching the maximum number of iterations.

An easy fix would be
```
self.converged = self.stopping_metric() <=  self.accuracy_threshold
```

**Comment by SepandKashani** [comment]
This issue pertains to Pycsou v1.
Pycsou v2's `Solver` API fixes this, hence we can safely close this issue.
